build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false
  excludes: ''

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 40 # lines of code without comments/blanks
